### ISSUE TITLE
Confirmar se repo está devidamente atualizado!!

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/litoral-sustentavel#1]
@diegorojas por favor, nos confirme se podemos partir daqui ou devemos tomar alguma ação para iniciar o trabalho da reforma do site.

**Comment by diegorojas** [comment]
Caros, não tenho acesso mais ao FTP para me certificar, mas lembro que sim. Toquemos, se perder algo é coisa muito simples que fiz no meio tempo.

A unica coisa especifica é que o visual do slider PostHighlights que esta na home tem um tema css próprio, que fica dentro da pasta do plugin.

**Comment by everaldomatias** [comment]
@willowmagrini se atente aos detalhes que o @diegorojas comentou e manda Brasa!!!

**Comment by willowmagrini** [comment]
Ok
