### ISSUE TITLE
Options para setar os destaques

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/litoral-sustentavel#10]
Adiciona option para a pessoa setar o ID dos dois destaques da Home.

**Comment by diegorojas** [comment]
Voltando, se são as areas em amarelo, acho que isso não deveria ser feito dessa forma.

**Comment by everaldomatias** [comment]
Então diga como deve ser @diegorojas.

**Comment by diegorojas** [comment]
Desculpa não explicar direito, tava na outra issue. "duas areas (titulo, imagem, texto) nas opções", que podem ter titulos tipo: Destaque inferior da home - direito / esquerdo

**Comment by diegorojas** [comment]
Acho que vai precisar tb de opções sobre o botão: URL e texto. E um if caso não tenha para não mostrar nada e não dar erro :)

**Comment by diegorojas** [comment]
Isso aqui é para dar flexibilidade. O Diogo disse que ali embaixo devem ser coringas, para poderem ser links para sites externos, com texto as vezes só introdutórios, as vezes não, ai nem tendo link e sendo só uma aviso, enfim. 

Acho que vale colocar o editor completo nas opções, podendo "Adicionar Midia" e tudo.

**Comment by willowmagrini** [comment]
@matheusgimenez
