### ISSUE TITLE
Layout de cada destaque

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/litoral-sustentavel#11]
Aplicar layout nos destaques sem imagem da Home.

![print-observatorio](https://cloud.githubusercontent.com/assets/1918474/6428935/e9b9b982-bf93-11e4-92d2-6a983a9d757c.jpg)

**Comment by diegorojas** [comment]
Eve, a ideia aqui é de serem dois widgets ou duas areas (titulo, imagem, texto) nas opções, serão cosias estáticas, que o Diogo quer poder mexer no conteudo.

**Comment by everaldomatias** [comment]
Sim, essa issue se trata da aplicação de CSS da issue #10

**Comment by diegorojas** [comment]
OK, queria ter falado isso ai na #10, mals.
