### ISSUE TITLE
Mapa do Site

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/litoral-sustentavel#12]
Fazer o mapa do site, para cada item pode ser feito um wp_nav_menu() para facilitar a administração e organização.

![print-observatorio](https://cloud.githubusercontent.com/assets/1918474/6428942/5d27c9c2-bf94-11e4-97e4-43bb81faa72f.jpg)

**Comment by diegorojas** [comment]
Isso já esta feito, são os menus "Site Map Coluna" que vão de 1 a 5. Acho que a questão é tirar um e renovar o CSS

**Comment by everaldomatias** [comment]
OK, fica a dica @willowmagrini
