### ISSUE TITLE
Logos de realização, convênio e apoio

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/litoral-sustentavel#13]
Essas imagens devem ser campos no Options Theme. Uma para cada um dos três itens.
![print-observatorio](https://cloud.githubusercontent.com/assets/1918474/6428951/a6ca9bb8-bf94-11e4-950b-1a6cf3ebeef9.jpg)

**Comment by everaldomatias** [comment]
@matheusgimenez aproveita que está trabalhando no Options, e faz essa issue também por favor?

**Comment by everaldomatias** [comment]
Se preocupe mais com o backend e funcionar na Home que o @willowmagrini arremata o CSS depois quando conseguirmos o layout v2.

**Comment by willowmagrini** [comment]
@matheusgimenez
