### ISSUE TITLE
Informações do Rodapé

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/litoral-sustentavel#14]
Essa informações podem ser campos no Options Theme.

![print-observatorio](https://cloud.githubusercontent.com/assets/1918474/6428957/cec9e100-bf94-11e4-96ab-3cbacd70f962.jpg)

**Comment by diegorojas** [comment]
Exato, mas também já está como option, do jeito antigo que faziamos, acho que precisa tirar e integrar com Options Framework

**Comment by everaldomatias** [comment]
Era isso que queria ouvir, qual Options iriamos usar. Criei uma nova issue para organizar isso #16

**Comment by willowmagrini** [comment]
@matheusgimenez
