### ISSUE TITLE
Adicionar Options Framework

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/litoral-sustentavel#16]
Pessoal, o tema já possui um Options, mas é baseado em uma classe e um pouco antigo. Vamos atualizar isso, o Diego sugeriu o Options Framework. Eu acho que outra alternativa seria usar a classe Options do Odin, o que acham @diegorojas @willowmagrini @matheusgimenez ?

**Comment by diegorojas** [comment]
Como preferirem manos, se não me engano o Odin usa uma base de códigos do Options tb :)

**Comment by matheusgimenez** [comment]
Tem que ser a do Odin hehe, ela é bem melhor que todo o resto ai heheh

**Comment by everaldomatias** [comment]
Vamos de Classe do Odin.

**Comment by diegorojas** [comment]
Da hora Brasa Devs.
