### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/litoral-sustentavel#2]
Menu com wp_nav_menu(), a direita temos a lupa de pesquisa e duas redes sociais.

A lupa, vamos usar esse exemplo: http://carpigianidobrasil.com.br/

![print-observatorio](https://cloud.githubusercontent.com/assets/1918474/6428817/6e5e91b8-bf8e-11e4-874b-b6b33f18f496.jpg)

**Comment by diegorojas** [comment]
A redes sociais que estao no tema atualmente perto do menu são com as opções velhas que usavamos, acho que precisa tirar e renovar com o Oprtion FrameWork para concentrar tudo o que terá de configuração a nova versão do tema.

**Comment by everaldomatias** [comment]
Abri a issue #16 para discutirmos qual Options usar.

**Comment by willowmagrini** [comment]
@matheusgimenez
