### ISSUE TITLE
Botao "Leia Todas" nao esta mais aparecendo

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#28]
Na Home - abaixo do carrossel de destaques há a seção de Notícias. na primeira versão no início do ano havia um botão - LEIA TODAS - em algum lugar. Ele sumiu em algum momento.

![image](https://cloud.githubusercontent.com/assets/5949986/10954218/cba7440e-8311-11e5-819b-a6e63e04a98e.png)

**Comment by willowmagrini** [comment]
@LuwkasLima  Esse botão virou o título de cada slider, correto?

**Comment by LuwkasLima** [comment]
@willowmagrini essa issue abri a primeira vez que conversei com as meninas por telefone, elas levantaram esse ponto eu eu disse que iriamos incluir como solucoes quando fizessemos o trampo.

To de acordo com voce quanto a isso, acho que posso convence-las sobre esse tema.
