### ISSUE TITLE
Logo mais imagem destacada

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/litoral-sustentavel#3]
Logo com link para Home e essa imagem, use a mesma estrutura que possui no site hoje, veja: http://litoralsustentavel.org.br/

![print-observatorio](https://cloud.githubusercontent.com/assets/1918474/6428828/d40f08bc-bf8e-11e4-969c-0fee58af741b.jpg)

**Comment by diegorojas** [comment]
Exato, a estrutura já esta no tema, é modificar css. É a estrutura de cabeçalhos que era padrão e que foi até o twentytwelve. 

A idéia é de manter o esquema do header de ir trocando as fotos, no esquema "aleatorias" la, precisa ver se faz uma mascara com essa curva ai ou se dá para fazer em css uma div por cima.

**Comment by everaldomatias** [comment]
Pois é, acho que vai precisar ser uma máscara com PNG, porque não conheço nada de CSS que faça esse ângulo, somente o canto arredondado.

**Comment by willowmagrini** [comment]
@LuwkasLima pelo que eu entendi da issue isso está feito, pode fechar?
