### ISSUE TITLE
CSS quebrado em pagina de Eixos Estrategicos

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#30]
Pessoal,

Precisamos arrumar o CSS dos boxes que estao na pagina abaixo:

http://litoralsustentavel.org.br/agenda/eixos-estrategicos-e-diretrizes-preliminares-da-agenda-regional/

**Comment by diogosp** [comment]
Isso não é um page-template ok? se tem algo errado é com o shortcodes.

**Comment by willowmagrini** [comment]
dei uma solução para a página específica, tem alguma outra que vocês sabem que usa esse shortcode?

**Comment by LuwkasLima** [comment]
@willowmagrini se subiu no Beta? Olhei a pagina abaixo:

http://beta.brasa.art.br/litoral-sustentavel/agenda/eixos-estrategicos-e-diretrizes-preliminares-da-agenda-regional/

A parada deve ser com o Shortcodes. Posso epdir ajuda do @matheusgimenez se for o caso. Ja fizemos isso pro Docklands..

**Comment by willowmagrini** [comment]
@LuwkasLima essa eu subi direto pra produção pq bug no site não rola.
