### ISSUE TITLE
Header >>  Menu e Cabeçalho

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#31]
Manter cabeçalho padrão utilizado pelo site:

![image](https://cloud.githubusercontent.com/assets/5949986/12367723/1c312810-bbaa-11e5-9cdb-9d7bdd6c1f62.png)

Layout: https://drive.google.com/open?id=0B8Nss0g77Q6cMVJSblRBZjhDR1E

**Comment by LuwkasLima** [comment]
@matheusgimenez segue comentarios:

1 - Imagem do cabeçalho não aparece:

![image](https://cloud.githubusercontent.com/assets/5949986/12729448/5f8c3de4-c8ec-11e5-87e9-d78ae24cd9fe.png)

**Comment by matheusgimenez** [comment]
Vish.. deve ser coisa do beta isso.. No local (com copia do site em produção) funciona.

Vou deixar esse como question, dps revemos junto quando vc estiver lendo.

**Comment by LuwkasLima** [comment]
Entao @matheusgimenez, na home existe uma imagem:

**Comment by LuwkasLima** [comment]
![image](https://cloud.githubusercontent.com/assets/5949986/12987414/9ad4abfc-d0c1-11e5-8157-8387e0c6f7ae.png)

Acredito que tenha a ver com o endereco da imagem:

![image](https://cloud.githubusercontent.com/assets/5949986/12987497/f2702ef4-d0c1-11e5-91a1-83ae35818b10.png)

![image](https://cloud.githubusercontent.com/assets/5949986/12987518/105d806a-d0c2-11e5-85cd-2636efde1d00.png)

**Comment by matheusgimenez** [comment]
Já vi o que ta rolando. Gambiarra do Willow, ele ta pegando o URL de forma errada.. vou resolver isso.

**Comment by LuwkasLima** [comment]
Perfect! Manda pra producao!
