### ISSUE TITLE
Content >> Page Template

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#32]
Entendo que esta é um Page-Template com ACF para inclusão de Imagens e Menu customizado:

![image](https://cloud.githubusercontent.com/assets/5949986/12368092/cbdd7040-bbad-11e5-8751-70939149a135.png)

Layout: https://drive.google.com/open?id=0B8Nss0g77Q6cMVJSblRBZjhDR1E

**Comment by LuwkasLima** [comment]
Colocando a explicação visual aqui pra esclarecer:

![image](https://cloud.githubusercontent.com/assets/5949986/12426989/4f67dc24-bea2-11e5-900d-c6ccdaf71ba0.png)

**Comment by LuwkasLima** [comment]
@matheusgimenez segue meus comentarios:

1 - Agora que as imagens são todas "quadradas" precisamos manter um espaçamento maior entre os elementos (seguir o layout):

![image](https://cloud.githubusercontent.com/assets/5949986/12729850/5ab89572-c8ee-11e5-8e51-0655faa57edd.png)

2 - Como gerencio o Menu?

![image](https://cloud.githubusercontent.com/assets/5949986/12729927/c09fc388-c8ee-11e5-9cb1-8d5338e97153.png)

**Comment by LuwkasLima** [comment]
Desconsidere o item 2

3 - Menu criado para o BAIXADA SANTISTA (com o mesmo nome) aparece tbm no LITORAL NORTE:

![image](https://cloud.githubusercontent.com/assets/5949986/12734990/d3bf4c34-c909-11e5-88d3-9f000de1e449.png)

4 - Formatar o menu para que os intens estejam mais espacados entre si e implementar um "hover" que inclui ums "seta" no intem com o mouse em cima como no layout:

![image](https://cloud.githubusercontent.com/assets/5949986/12735011/086ead12-c90a-11e5-8340-9a3817255596.png)

**Comment by matheusgimenez** [comment]
1: Resolvido 

3: O ultimo menu criado sempre vai aparecer nos locais onde não tem menu setado.

4 / Seta: precisa mesmo? eu fiz esse menu ter cores gerenciaveis.. colocar uma seta levando em conta a cor vai dar certo trabalho..

4 / Espaço: Resolvido

**Comment by LuwkasLima** [comment]
1 - @matheusgimenez ainda nao ta 100%. Da mais uma espacada ai pra ficar supimpa, por gentileza:

**Layout:**

![image](https://cloud.githubusercontent.com/assets/5949986/12987237/c1399e84-d0c0-11e5-9ead-dc1c4c4d6ce4.png)

**Como esta:**

![image](https://cloud.githubusercontent.com/assets/5949986/12987208/a7efdc2c-d0c0-11e5-97b2-0561992600ad.png)

3 - Saquei. Temos que colocar isso na documentacao pra que eles saibam...

![image](https://cloud.githubusercontent.com/assets/5949986/12987299/0df8a1ac-d0c1-11e5-810e-af6d1089d85f.png)

4 - /Seta: Tudo bem. No entanto, em vez de usarmos o "sublinhado" pra mostrar que o link eh clicavel. Nao podemos tranformar todo o retangulo em um botao que muda de cor no Hover?

![image](https://cloud.githubusercontent.com/assets/5949986/12987377/7482e1e4-d0c1-11e5-8ed7-85cd87c76b02.png)

4 /Espaco: Perfeito!

**Comment by matheusgimenez** [comment]
1 - Resolvido.

4 /Seta: Resolvido, ficará da cor escolhida pra borda.

**Comment by LuwkasLima** [comment]
OK! Manda pra producao!
