### ISSUE TITLE
Footer >> Rodapé padrão

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#34]
Aplicar rodapé padrão da Home (sem os videos):

![image](https://cloud.githubusercontent.com/assets/5949986/12368278/82de8724-bbaf-11e5-82ac-0ea40bf632a9.png)

Layout: https://drive.google.com/open?id=0B8Nss0g77Q6cMVJSblRBZjhDR1E

**Comment by LuwkasLima** [comment]
@matheusgimenez vc acha que podemos fazer o favor de colocar uma imagem sem fundo desta vez? Essa imagem incluida no rodape com fundo de outra cor da vergonha...kkk

![image](https://cloud.githubusercontent.com/assets/5949986/12729998/21f0bd40-c8ef-11e5-996e-7a9665d667b7.png)

**Comment by matheusgimenez** [comment]
Resolvido

**Comment by LuwkasLima** [comment]
Boa garoto!...obrigado
