### ISSUE TITLE
Header >> Cabeçalho com Imagem Destacada

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#35]
Este template já não possui o mesmo Cabeçalho das outras páginas.

1 - Logo simples seguido do Título da Página e abaixo o nome da Triagem (Veja Página Triagem):

![image](https://cloud.githubusercontent.com/assets/5949986/12368348/3caed85c-bbb0-11e5-8800-39d47b46ee75.png)

2 - A imágem abaixo deve corresponder a Imagem Destacada

Layout: https://drive.google.com/open?id=0B8Nss0g77Q6cU2x0bzJvQUdvdFU

**Comment by LuwkasLima** [comment]
@matheusgimenez segue o que precisa ser arrumado:

1 - Proporção do Logo com o Título precisa ficar o mais próximo do Layout posssível;

![image](https://cloud.githubusercontent.com/assets/5949986/12727432/b1c6db28-c8e2-11e5-8d29-7d67ade4fe30.png)

2 - Espaçamento do título de 2 linhas e distancia com sub-título precisa ser revista (pra ficar mais próximo do Layout):

![image](https://cloud.githubusercontent.com/assets/5949986/12727465/d5c2dc52-c8e2-11e5-928c-415b699f5b50.png)

3 - A linha acima da imagem está muito "grossa". Entendo que deva ser de no máximo 2px segundo layout:

![image](https://cloud.githubusercontent.com/assets/5949986/12727502/f598b1c8-c8e2-11e5-8909-eaf8035100e4.png)

4 - O header que apresenta a imagem destacada precisa ser de tamanho fixo (olha o que aconteceu quando coloquei uma foto grande):

![image](https://cloud.githubusercontent.com/assets/5949986/12727548/1a226408-c8e3-11e5-8af0-93e9d95b41fa.png)

5 - Fonte e core do sub-titulo não corresponde ao Layout aparentemente (acredito ser um cinza do mesmo tom do Título):

![image](https://cloud.githubusercontent.com/assets/5949986/12727615/5598420a-c8e3-11e5-9a75-54543e32f320.png)

@everaldomatias ajude aqui com apontamentos adicionais ou para guia-nos quanto a cores, tamanhos e etc...

**Comment by LuwkasLima** [comment]
Página criada de exemplo:

http://beta.brasa.art.br/litoral-sustentavel/dialogos-sobre-grandes-empreendimentos-no-litoral-paulista/

**Comment by matheusgimenez** [comment]
Feito.

**Comment by LuwkasLima** [comment]
Nao esta perfeitamente alinhada com o Layout, mas como nao temos o PSD eu entendo que fica dificil de fato. E nao esta ruim do jeito que esta. Entao seguimos!

Tudo OK!
