### ISSUE TITLE
Content >> Conteúdo Dinâmico com Menu e Abas

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#36]
Conteúdo dinâmico com menu ao lado esquerdo e apresentação de conteúdo ao lado direito.

![image](https://cloud.githubusercontent.com/assets/5949986/12368398/ba96286a-bbb0-11e5-8697-1b6477d000d4.png)

Layout: https://drive.google.com/open?id=0B8Nss0g77Q6cU2x0bzJvQUdvdFU

**Comment by LuwkasLima** [comment]
@matheusgimenez como eu defino qual MENU deve ser lincado a esta página? Como terão varias páginas criadas com esse template, precisamos da flexibilidade de criar um MENU novo e linca-lo a esta página em especifico.

![image](https://cloud.githubusercontent.com/assets/5949986/12728060/a100259e-c8e5-11e5-808b-5b617b14618f.png)

**Comment by matheusgimenez** [comment]
Você cria um menu com o mesmo nome da página.

Todos itens do tipo página desse menu, vão abrir do lado direito em ajax. Porem, se ao invés de selecionar uma página simplesmente jogarmos em Links personalizados, eles não vão abrir com ajax, vão redirecionar para a página.

**Comment by LuwkasLima** [comment]
OK!

Precisamos somente ir anotando todos estes pontos pra poder enviar a cliente. Ou seja, precisamos de uma pequena documentacao pra entregar pra eles...
