### ISSUE TITLE
Content >> Área em Destaque Simples

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#37]
Área de destaque para Post (?), com botão de Leia Mais:

![image](https://cloud.githubusercontent.com/assets/5949986/12368431/e8e36d68-bbb0-11e5-97fb-0783b334d680.png)

Layout: https://drive.google.com/open?id=0B8Nss0g77Q6cU2x0bzJvQUdvdFU

**Comment by LuwkasLima** [comment]
@matheusgimenez como vc fez para aparecer a area de destaque? Eu coloquei o link para um posts dentro do Campo que voce disponibilizou no template page mas nao aparece nada:

![image](https://cloud.githubusercontent.com/assets/5949986/12728338/f8e2f664-c8e6-11e5-81af-6212b9ed86fa.png)

**Comment by LuwkasLima** [comment]
Descobri! =)

Segue comentarios:

1 - Botão "Leia Mais" precisa ficar "colado" ao fim da área de destaque, como se fizesse parte do fundo quadriculado. Independentemente do tamanho do texto e imagem (seguindo layout):

![image](https://cloud.githubusercontent.com/assets/5949986/12729707/a2b8c5a0-c8ed-11e5-99a5-1ae12bb905cc.png)

**Comment by matheusgimenez** [comment]
Tem certeza dessa? Eu vou consultar o @everaldomatias, pq acho que foi erro de layout.. me causa certa estranheza esse botão grudado no fundo '-'

**Comment by everaldomatias** [comment]
@matheusgimenez eu condordo em deixar um margin entre o botão e a extremidade do quadro.
Falhei no layout mesmo. Mas vejam o que acham melhor.

**Comment by LuwkasLima** [comment]
@matheusgimenez e @everaldomatias eu entendo a preocupacao, mas como o Layout foi visto pelo cliente e elas aprovaram, entao sabemos que pra elas eh melhor que seja como no Layout. Mas vou deixar como esta para ver o que acham, ja que eh uma mudanca nao muito brusca do Layout.

No entanto, na duvida, vamos SEMPRE seguir o layout ok? Porque quando comecamos o desenvolvimento, o Layout foi aprovado pelo cliente e assim evitamos dores de cabeca posteriores.

Ta ok! =)
