### ISSUE TITLE
Content >> Archive de Últimas Publicações

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#38]
Area de archive com últimas publicações e botão de "Carregar Mais" (como o do Mundial):

![image](https://cloud.githubusercontent.com/assets/5949986/12368463/3b7c86a4-bbb1-11e5-9a66-2f6de47fe692.png)

Layout: https://drive.google.com/open?id=0B8Nss0g77Q6cU2x0bzJvQUdvdFU

**Comment by LuwkasLima** [comment]
@matheusgimenez segue detalhes que precisam ser re-feitos:

1 - Botão "Leia Mais" precisa ser mais "fino" e comprido. Mantendo-se um mesmo tamanho em todos os boxes, seguindo Layout:

![image](https://cloud.githubusercontent.com/assets/5949986/12728413/5d66488e-c8e7-11e5-8bbd-d234454562c5.png)

**Comment by LuwkasLima** [comment]
2 - Fundo da imagem "Ver todas publicações" pode ser visto:

![image](https://cloud.githubusercontent.com/assets/5949986/12728509/bdb4a01e-c8e7-11e5-8179-8a725cb06e7d.png)

**Comment by matheusgimenez** [comment]
Feito

**Comment by LuwkasLima** [comment]
Ta lindo!

**Comment by LuwkasLima** [comment]
@matheusgimenez encontrei um bug na listagem de ultimas noticias. Dependendo da taxonomia que escolho, as vezes aparece desse jeito:

![image](https://cloud.githubusercontent.com/assets/5949986/13645280/d47a3f50-e5ef-11e5-9479-b3ca3e9c1de5.png)

**Comment by LuwkasLima** [comment]
@matheusgimenez to fechando esse pq criei um outro especificamente para a quebra de CSS dessa lista de posts. Issue #54
