### ISSUE TITLE
Header >> Cabeçalho com Logo e Imagem Destacada

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#40]
Aplicar cabeçalho com Logo do Litoral e área de titulo sobre imagem destacada "esbranquiçada":

![image](https://cloud.githubusercontent.com/assets/5949986/12368546/fdff5120-bbb1-11e5-9d62-d1cfde145b99.png)

**Comment by LuwkasLima** [comment]
@matheusgimenez seguem apontamentos:

1 - Diminuir a distancia do logo para a imagem de destaque, aumentando a largura da imagem de destaque para cima (ficando mais proximo do layout):

![image](https://cloud.githubusercontent.com/assets/5949986/12754844/82bd0aa4-c992-11e5-8219-d205c4edce3f.png)

2 - Centralizar Titulo:

![image](https://cloud.githubusercontent.com/assets/5949986/12754865/9624ce2e-c992-11e5-839a-378642b1d299.png)

**Comment by LuwkasLima** [comment]
Pagina de teste criada: http://beta.brasa.art.br/litoral-sustentavel/equipe-de-monitoramento-lucas/

**Comment by matheusgimenez** [comment]
Feito

**Comment by LuwkasLima** [comment]
1 - A distancia do Logo pra imagem ficou perfeita. No entanto agora me parece que o tamanho da Imagem de destaque esta um pouco "fina" demais. Se aumentarmos um pouco mais fica melhor:

![image](https://cloud.githubusercontent.com/assets/5949986/12985692/82ce8f3a-d0b9-11e5-9f6a-06b5a45e9ea3.png)

2 - Centralizar Titulo: O titulo ainda nao ta centralizado.

![image](https://cloud.githubusercontent.com/assets/5949986/12985714/9b83871a-d0b9-11e5-8dc7-bedcea4a5e42.png)

**Comment by matheusgimenez** [comment]
1 - Resolvido.

2 - Pode me falar qual a sua resolução? to usando um media query nesse item, mas acho que não ta aplicando pra vc.

**Comment by LuwkasLima** [comment]
2 - Aqui Centralizou. So precisa ajeitar a fonte do titulo pra ficar um pouco maior e proxima do Layout

**Comment by matheusgimenez** [comment]
Resolvido

**Comment by LuwkasLima** [comment]
@matheusgimenez como faco pra que apareca os 3 slides juntos como no layout ao inves de um slide de cada vez?

![image](https://cloud.githubusercontent.com/assets/5949986/13186538/43a5f68c-d70c-11e5-9f4d-1078e44f7351.png)

**Comment by LuwkasLima** [comment]
Perfeito!
