### ISSUE TITLE
Content >> Area de Texto e Notícias

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#41]
Área livre de texto centralizado com carrossel(?) de notícias:

![image](https://cloud.githubusercontent.com/assets/5949986/12368576/4c16c618-bbb2-11e5-9f84-7a141828bc2c.png)

Layout: https://drive.google.com/open?id=0B8Nss0g77Q6ccWRhQkV4OHBsZ00

**Comment by matheusgimenez** [comment]
É um slider ou são só 3 imagens mesmo?

**Comment by diogosp** [comment]
É pra puxar posts como "Destaques", este era o pensamento. pra ficar beeem programável e editável pra outras coisas.

**Comment by matheusgimenez** [comment]
@diogosp destaques é uma categoria?

**Comment by diogosp** [comment]
@matheusgimenez temos que ver com o @everaldomatias. A mecânica interna eu não pensei, deixei pra vocês.

**Comment by diogosp** [comment]
Originalmente não foi pensado como Slider, certo @everaldomatias ? 
a página completa é um template que será usada pra várias coisas diferentes. Então precisa puxar categorias que se indique em algum lugar específico pra que fique customizável toda vez. @matheusgimenez to registrando aqui tb.

**Comment by LuwkasLima** [comment]
@diogosp, @matheusgimenez e @everaldomatias eu entendo que a melhor forma aqui eh usar o brasa Slider e criar um slider chamdo Destaque - Equipe. Vai funcionar igualzinho a solução que propomos à Home Page do Lirotral, onde elas vão eleger quais posts aparecem na seção de destaque. Faz sentido?

**Comment by diogosp** [comment]
Pensa na mecânica da página. Imaginem que existam 4 equipes que precisem de paginas. Portanto é uma estrutura que precisa puxar categoria especifica pra cada "equipe". Pensando que "equipe" tb será outra coisa.

**Comment by LuwkasLima** [comment]
@matheusgimenez seguem meus comentarios:

1 - Com base na conversa acima, vamos precisar implementar a mesma logica implementada na landing-page "Camara" para que uma categoria de post seja apresentada nos destaques:

![image](https://cloud.githubusercontent.com/assets/5949986/12755358/acfe367e-c994-11e5-98c8-9fec4e320e52.png)

![image](https://cloud.githubusercontent.com/assets/5949986/12755389/c49342b6-c994-11e5-8fb4-8ee7495ad3f5.png)

2 - Deve apresentar 3 destaques e imagino que em um carrossel seria o mais indicado.

**Comment by matheusgimenez** [comment]
Eu já fiz esse slider.. acabei não explicando, me desculpe.

Ele é um brasa slider, você cria um novo brasa-slider com o nome: NOME DA PÁGINA Destaques.

Veja o exemplo:
![screenshot-localhost 2016-02-09 14-03-13](https://cloud.githubusercontent.com/assets/4724804/12921795/f1c9e7f2-cf35-11e5-801d-bb3e40f38d5a.png)

No mais, corrigi um probleminha de CSS nesse slider.

**Comment by LuwkasLima** [comment]
@matheusgimenez eu entendi a solucao e esta alinhada com um dos meus comentarios anteriores aqui:

> @diogosp, @matheusgimenez e @everaldomatias eu entendo que a melhor forma aqui eh usar o brasa Slider e criar um slider chamdo Destaque - Equipe. Vai funcionar igualzinho a solução que propomos à Home Page do Lirotral, onde elas vão eleger quais posts aparecem na seção de destaque. Faz sentido?

No entanto, fiz um teste aqui com a pagina da Equipe que criei pra mim e nao funcionou:

![image](https://cloud.githubusercontent.com/assets/5949986/12985553/e4904e80-d0b8-11e5-8cf6-6029a9a1637d.png)

Alem disso, acho que talvez fique um pouco complicado pra eles entenderem o mecanismos. Mas para sermos praticos, verifica o problema acima e explicamos pra eles como trabalhar com o Slider Brasa. Mesmo porque, a reforma que faremos na Home Page usara a mesma logica.

Coloquei de volta "Para Fazer", assim vc pode verificar esse problema.

**Comment by matheusgimenez** [comment]
Você usou **-** no titulo da página e **—** no título do slider.

**Comment by matheusgimenez** [comment]
Veja agora:

http://beta.brasa.art.br/litoral-sustentavel/equipe-de-monitoramento-lucas/

**Comment by LuwkasLima** [comment]
@matheusgimenez olha os espacos!!...hehehe

Se liga tbm no tamanho da Fonte do Titulo da Pagina...

**Layout:**

![image](https://cloud.githubusercontent.com/assets/5949986/13067340/ae187d4e-d434-11e5-837b-49b45bb1dcf9.png)

**Atual:**

![image](https://cloud.githubusercontent.com/assets/5949986/13067373/dbc4ff74-d434-11e5-8bb4-f6e64e429214.png)

**Comment by matheusgimenez** [comment]
Resolvido

**Comment by diogosp** [comment]
Eu vi que vcs me marcaram aqui. Precisa de algum pitaco ainda @LuwkasLima ??

**Comment by LuwkasLima** [comment]
Ta suave!

**Comment by matheusgimenez** [comment]
Revisei o mobile dessa página. 

Só ficou um problema:

O shortcode do slider que antes continha o codigo de configurações do slickjs vai precisar ser definido nas configurações do slider, já que existe um problema com o parse do caracter **[ e ]** pelo WP.

Segue o codigo:

{"dots": false,"infinite": true,"speed": 3000, "autoplay":true, "autoplaySpeed": 5000, "slidesToShow": 3, "responsive": [ {"breakpoint": 800, "settings": { "slidesToShow": 1, "slidesToScroll": 1 }}]}

**Comment by LuwkasLima** [comment]
@matheusgimenez beleza, vamos deixar assim, caso vc tenha uma ideia legal fazemos posteriormente. So ficou uns pelos de Pente-fino:

1 - Faltou o efeito que foi feito no Residuo Zero Brasil, com o texto sumindo aos poucos

![image](https://cloud.githubusercontent.com/assets/5949986/13187085/cd1a4c4a-d70e-11e5-9e1b-d88a3d563296.png)

2 - O botao pode ficar um pouco mais afastado do texto pra ficar menos truncado..
