### ISSUE TITLE
Content >> Área de Video + Galeria de Imagens

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#43]
Incluir área para 1 video e abaixo galeria de imágens (como no Quinta Essentia talve?):

![image](https://cloud.githubusercontent.com/assets/5949986/12368638/e3b54d64-bbb2-11e5-8d09-6b1f5eefaebc.png)

As imagens precisam abrir maiores na tela (imagino com um Modal ou galeria padrão do WP)

**Comment by LuwkasLima** [comment]
@matheusgimenez segue detalhes:

1 - Posicionar o Video centralizado (tentei fazer atraves do painel do WP mas nao funciona.

![image](https://cloud.githubusercontent.com/assets/5949986/12755964/2a9bb384-c997-11e5-937c-252fc279ad84.png)

2 - Aumentar a distancia entre o titulo e os objetos:

![image](https://cloud.githubusercontent.com/assets/5949986/12755953/20dcd120-c997-11e5-8064-00b9d4f844d2.png)

3 - Precisamos pensar em como fazer para as imagens abrirem em uma galeria. Infelizmente, as opcoes de galeria do Wordpress nao estao aparecendo (nao sei se eh por causa do MU). As unicas opcoes disponiveis sao: Nao abrir maior, Abrir maior em uma pagina zuada e abrir maior no browser.

![image](https://cloud.githubusercontent.com/assets/5949986/12756121/e3284354-c997-11e5-9feb-ac9453ab11df.png)

**Comment by matheusgimenez** [comment]
1: Você tá embedando o video de qual forma? Aqui se eu simplesmente copiar e colar no editor o URL do vídeo no YT ele centraliza certinho.

2: Estou resolvendo.

3: Aqui em localhost (estou com copia do site atual) funciona sem problemas as galerias do JP abrindo na aquele modal padrão dele.

**Comment by LuwkasLima** [comment]
1 - Eu copiei e colei tbm, mas agora esta centralizado (nao se se vc fez algo pra checar isso).

2 - Nao ficou exatamente como no Layout, mas esta bom o suficiente. Novamente, sem o PSD fica mais complicado pra vc, entao vou dar uma flexibilizada eh caro. =)

3 - Beleza, se esta funcionando no Local Host, vamos confiar..

Esta OK!
