### ISSUE TITLE
Content >> Formulário de Contato

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#44]
Formulário de contato simples com a equipe de monitoramento desta página em específico:

![image](https://cloud.githubusercontent.com/assets/5949986/12368663/23096b76-bbb3-11e5-9701-c9f6a2c7ed99.png)

Layout: https://drive.google.com/open?id=0B8Nss0g77Q6ccWRhQkV4OHBsZ00

**Comment by LuwkasLima** [comment]
@matheusgimenez tive que ativar o Jetpack no beta pra poder funcionar o formulario. Verifiquei que o Jetpack e o formulario estao ativos no site em producao, entao nao sera problema. Seguem comentarios:

1 - Reduzir o botao "Enviar" para que fique igual ao Layout:

![image](https://cloud.githubusercontent.com/assets/5949986/12756390/2c246e88-c999-11e5-8796-5d0e59f3b67e.png)

2 - Conseguimos fazer com que o Titulo dos campos esteja como no layout (dentro do campo e nao fora)?

**Comment by matheusgimenez** [comment]
O formulário do jetpack tem essas limitações.. não consigo na estrutura dele fazer essas modificações..

Poderiamos usar o contact form 7.. mas o pessoal do Litoral Sustententavel já está acostumado com o JP.

**Comment by LuwkasLima** [comment]
@matheusgimenez nao se preocupa. Deixamos com o JetPack mesmo obviamente.

@everaldomatias e @diegorojas precisam ficar mais atentos na hora de criar os layouts. Tomar o cuidado de verificar como ficara usando o JetPack ou o Contact Form 7.

Esta OK!
