### ISSUE TITLE
[Pergunta] O WP do Litoral esta na versao 4.3 e o Beta em 4.4

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#46]
@matheusgimenez verifiquei que nosso beta esta na versao 4.4 e o ambiente de producao do litoral esta no 4.3. Eu entendo que isso pode ser um problema, vamos precisar atualizar o ambiente deles para 4.4?

Eu terei que avisa-los que isso precisa entrar no orcamento, caso essa seja a unica forma de resolver o problema. Fico no aguardo do seu posicionamento.

**Comment by matheusgimenez** [comment]
4.3 não é um problema nesse caso, já que não estamos usando nenhuma função de term meta até agora. Se precisarmos de algo assim (term_meta) ai precisaremos pensar em atualizar.

**Comment by matheusgimenez** [comment]
@matheusgimenez Pera ai que acho que vai ser necessario em agenda sim :(

**Comment by LuwkasLima** [comment]
@matheusgimenez nao esquece de me avisar aqui pra que eu possa comecar o processo de estimar tempo e custo pra isso e possamos avisar o cliente. ok?

**Comment by LuwkasLima** [comment]
@matheusgimenez vamos marcar para subir para produção amanhã por volta das 14h30 pra verificar esse tema e subir pra produção? Não suba antes de falar comigo sobre esse tema da versão. Talvez tenhamos que adicionar horas pra atualizar o ambiente deles ok?
