### ISSUE TITLE
Header >> Logo + Titulo da pagina Agenda

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#47]
Aqui o header eh bem simples, Menu padrao com Logo do Litoral seguido do titulo da Pagina. Lembrando que essa pagina nao sera usada mais do que 1 vez. Ela eh uma pagina fixa chamada "AGENDA DE DESENVOLVIMENTO SUSTENTAVEL"

![image](https://cloud.githubusercontent.com/assets/5949986/12757224/bb6e7a86-c99c-11e5-8a98-260c4eb1aacb.png)

**Comment by LuwkasLima** [comment]
@matheusgimenez o titulo parece um pouco desalinhado pra esquerda e a fonte parece diferente. Voce usou o mesmo codigo do titulo das landing pages?

![image](https://cloud.githubusercontent.com/assets/5949986/13191902/ed6444ba-d72c-11e5-9350-1e421b6d42a0.png)

**Comment by matheusgimenez** [comment]
Sim, é o mesmo.
