### ISSUE TITLE
Apresentacao >> Menu + Conteudo simples com Titulo

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#48]
Area de apresentacao da Agenda com menu com (hover em azul) e selecao em Ajax para apresentacao do conteudo a direita. Esse conteudo precisa ter Titulo e formatacao de texto:

![image](https://cloud.githubusercontent.com/assets/5949986/12757511/f39ef556-c99d-11e5-8369-5bafe089c7ea.png)

**Comment by matheusgimenez** [comment]
Feito

**Comment by LuwkasLima** [comment]
@matheusgimenez ficou da hora, a seta ta um pouco diferente do layout, mas ficou estiloso.

So tenho um ponto a resolver:

1 - O elementos parecem estar muito desproporcionais em relação ao Layout:

Como está:

![image](https://cloud.githubusercontent.com/assets/5949986/13191942/4368b9d6-d72d-11e5-90bd-55650298153e.png)

Layout:

![image](https://cloud.githubusercontent.com/assets/5949986/13191963/61294922-d72d-11e5-9591-5e83b49352b7.png)

O enquadramento e o tamanho desse menu com conteúdo dinamico parecem estar melhor dimencionados no Layout. Veja o que acha?

**Comment by matheusgimenez** [comment]
O problema é que se eu diminuo o tamanho menu, ele quebra minha seta (fiz com css) :(

Eu acho que esse tamanho está legal, de qlq forma

**Comment by LuwkasLima** [comment]
Beleza, entao aumenta o Titulo pra ficar mais BOLD e compensar o tamanho do Menu...que vc acha @matheusgimenez ?
