### ISSUE TITLE
Filtros >> Taxonomias + Busca + Area de Intrucoes

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#49]
Esta eh a area de filtro que dara dinamica e poder de navegacao a pagina AGENDA. Ela possui os seguintes elementos:

1 - Taxonomia EIXOS que sao 3 atualmente. Precisam aparecer com seus respectivos icones para diferenciacao.

2 - Taxonomia TEMAS sao diversos e precisam ter cores diversas tambem para que sejam diferenciados.

3 - Campo de Busca por palavra chave (entendo que precisa ser uma busca inteligente)

Obs.: As duas taxonomias em conjunto com o campo de busca podem ser usadas durante a filtragem (ou seja, somadas para trazer o resultado esperado)

4 - Area de texto pequena para incluir uma rapida explicacao de como usar os filtros para encontrar as Acoes da Agenda.

5 - Este "Circulo" deveria ser uma LUPA (icone de busca)

![image](https://cloud.githubusercontent.com/assets/5949986/12757606/5f0ec906-c99e-11e5-9ec8-a76d217c0a7e.png)

**Comment by matheusgimenez** [comment]
Feito.

Só explicando o ponto 4: isso vai ser o content da página Agenda de Desenvolvimento. Use a tag h1 para o titulo.

**Comment by matheusgimenez** [comment]
Só mais um ponto: A area em azul não apliquei a textura de fundo pq não consigo refazer o efeito (estou sem o PSD). Alguem tem alguma sugestão de como aplicarmos isso?

Se for algo de Photoshop e o @everaldomatias puder me falar como fazer..

**Comment by LuwkasLima** [comment]
@matheusgimenez criei no BETA a página da AGENDA e um Post chamado Ação 1 e não aparece na area de Ações da Página Agenda:

Post: http://beta.brasa.art.br/litoral-sustentavel/2016/02/19/acao-1/

Agenda: http://beta.brasa.art.br/litoral-sustentavel/agenda-de-desenvolvimento-sustentavel/

![image](https://cloud.githubusercontent.com/assets/5949986/13192150/9e660392-d72e-11e5-9bcb-f145233a9bbd.png)

Sobre a Textura, o @everaldomatias deve te passar na segunda e sobre a ideia do texto de introdução, fta certinho manter no conteudo da pagina!

**Comment by LuwkasLima** [comment]
Aqui eh só meter a textura que falta e esperar a definição das cores do novo layout.

**Comment by LuwkasLima** [comment]
@matheusgimenez  como conversado por chat, vamos RETIRAR o filtro TEMAS por pedido da cliente, OK?

**Comment by matheusgimenez** [comment]
Feito
