### ISSUE TITLE
Área de Widgets

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/litoral-sustentavel#5]
Configurar área de widgets para Home.

![print-observatorio](https://cloud.githubusercontent.com/assets/1918474/6428872/63496bf6-bf91-11e4-8bbc-1ff99953ced4.jpg)

**Comment by diegorojas** [comment]
Tem uma area de widget secundaria herdada do twentyten que não é usada, poderia usar ela.

**Comment by everaldomatias** [comment]
OK, fica a dica @willowmagrini.
