### ISSUE TITLE
Archive >> Lista de Acoes (Taxonomias + Titulo)

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#50]
Esta eh a area dinamica que ira se movimentar e ir filtrando o conteudo com base nos filtros que sao aplicados na area de filtro acima.

Entendo que nao existe a necessidade de apresentar todos os itens de uma vez (podemos ter o "Veja Mais" abaixo para carregar mais itens). No entanto, o filtro precisa ser aplicado a tudo obviamente:

![image](https://cloud.githubusercontent.com/assets/5949986/12757914/a9e4f148-c99f-11e5-82ca-8bc540a6dcae.png)

Atente aos seguintes itens:

1 - Titulo da Acao com fundo preto com transparencia

2 - Cor da Taxonomia TEMAS

3 - Icone da Taxonomia EIXOS

![image](https://cloud.githubusercontent.com/assets/5949986/12757940/d88b1bbc-c99f-11e5-9583-bfc64a6de1f2.png)

**Comment by matheusgimenez** [comment]
Feito essa. Mas acho que errei.. era pra ser um CPT né? acabei adicionando como posts.. se for um problema posso rever durante a semana.

**Comment by LuwkasLima** [comment]
Como explicado na outra issue, fiz um teste e não rolou...

**Comment by LuwkasLima** [comment]
@matheusgimenez ficou muito legal cara, parabens!

Seguem meus comentarios:

1 - Precisamos colocar uma mensagem com tamanho de fonte maior pra manter um espaco e talvez uma imagem pra retratar que a busca nao trouxe nenhuma acao. Pensa em algo divertido e util, do tipo: Ops! Nao existem acoes com estas caracteristicas, desculpe! Tente novamente...

![image](https://cloud.githubusercontent.com/assets/5949986/13192483/1609e65e-d732-11e5-9f0a-b7862c0bf478.png)

2 - Quando um filtro esta selecionado, nao fica muito claro que ele esta selecionado. Eu acho que aplicar um after (acho que eh isso), pra ele ficar Cinza Escuro quando esta selecionado iria cair bem aqui:

![image](https://cloud.githubusercontent.com/assets/5949986/13192494/36a7214c-d732-11e5-86bc-e1d9e4a316ef.png)

3 - Tem uma "sobrinha" no retangulo que fica abaixo do titulo da ação:

![image](https://cloud.githubusercontent.com/assets/5949986/13192525/a88ceff8-d732-11e5-9a00-178f1de87427.png)

4 - Tem algum jeito de aplicar um Hover nos boxes de cada ação e quando a pessoa passa o Mouse os outros boxes ficam escuros, ou ele fica mais claro, ou ele fica um poquinho maior. Algo que destaque ele dos outros quando o mouse passa em cima?

![image](https://cloud.githubusercontent.com/assets/5949986/13192546/dfa51ea2-d732-11e5-86a4-f5db8e2d1f37.png)

5 - Outra coisa eh o "motion" dos elementos quando selecionamos os filtros. Existe alguma forma de rolar um "fade out" dos outros ao invez de aparecer esse simbolo de carregar?

![image](https://cloud.githubusercontent.com/assets/5949986/13192590/4402d830-d733-11e5-80cb-1216423cea9b.png)

Olha esse site: http://www.nytimes.com/interactive/2012/12/24/sports/basketball/pick-your-all-time-new-york-city-nba-team.html

Acho que eh isso, se tiver mais aviso..

**Comment by LuwkasLima** [comment]
@matheusgimenez 4 e 5 voce nao conseguiu fazer eh isso?

**Comment by matheusgimenez** [comment]
o 4 eu fiz, o 5 já tem: os elementos quando carregados dão um "pulo".

**Comment by LuwkasLima** [comment]
@matheusgimenez beleza! Ta ok!
