### ISSUE TITLE
Layout >> Mudança Na Lógica do Layout

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#52]
@everaldomatias como explicado no chat, precisamos refazer o Layout para retirar as cores de cada TEMA e buscar uma solução pra manter essas cores nos Boxes, por me parece que fica visualmente mais interessante.

Cada Ação tem EIXO e TEMA como taxonomia... Cada Ação faz parte apenas de 1 EIXO e portanto pode ser uma categoria unica de uma ação.. Já TEMAS é diferente, uma Ação pode ter **Varios TEMAS**. 

![image](https://cloud.githubusercontent.com/assets/5949986/13192682/5fff1d18-d734-11e5-8d6c-83d47cd35767.png)

Minha sugestão de solução:
 1 - Cor lateral alinhada com a cor do Logo
 2 - Remoção das tags abaixo

![image](https://cloud.githubusercontent.com/assets/5949986/13192661/2188c3e0-d734-11e5-973f-063bbd72a93d.png)

**Comment by LuwkasLima** [comment]
@everaldomatias essa é a issue (junto com a #53 ) que precisa ser feita hoje a noite. Basicamente voce precisa pensar em uma nova lógica, porque TEMAS não pode ter cores ou simbolos, já que uma AÇÃO pode ter 1 ou mais TEMAS.

No entanto, eu gosto da corzinha do lado esquedo dos quadrados e por isso acho que podemos definir 1 cor pra cada ICONE que foi criado para os EIXOS. Dessa forma, o Icone e a COR serão um conjunto que definirá à qual Eixo pertence a Ação.

**Comment by LuwkasLima** [comment]
@everaldomatias como conversado por chat, vamos RETIRAR o filtro TEMAS por pedido da cliente

**Comment by everaldomatias** [comment]
Feitas as alterações. Veja se é isso @LuwkasLima 

![litoral3-layout-agenda-v4](https://cloud.githubusercontent.com/assets/1918474/13269827/ab10612c-da68-11e5-9dab-2ade5edb8248.jpg)

**Comment by LuwkasLima** [comment]
@everaldomatias mano,

Ficou certinho, o unico problema eh o seguinte:

1 - Voce esquecei de colocar os icones nos Quadrados da terceira Coluna!
2 - Esse Cinza eh bem estranho. Ele esta nas cores do ID Visual?

**Comment by everaldomatias** [comment]
@LuwkasLima 

![litoral3-layout-agenda-v4](https://cloud.githubusercontent.com/assets/1918474/13293945/8c72fb2e-db00-11e5-9a00-635491eadbbc.jpg)

**Comment by LuwkasLima** [comment]
Esta sob revisao do pessoal do Litoral. Obrigado @everaldomatias
