### ISSUE TITLE
Layout >> Mudança Na Single de Ações

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#53]
@everaldomatias como vamos mudar a logica de cores para TEMAS, isso significa que provavelmente vamos ter que mudar o layout da Single, pois ela apresenta as cores utilizadas pelo TEMAS:

![image](https://cloud.githubusercontent.com/assets/5949986/13192709/a94fb568-d734-11e5-8014-35f3db3dc21e.png)

Sugestão: Mudar essa cor para refletir a cor do EIXO (caso a solução que eu propus na outra issue seja aceita)

Apresentar no topo todas as taxonomias.

![image](https://cloud.githubusercontent.com/assets/5949986/13192778/5a1cbefe-d735-11e5-9200-911cb9603df2.png)

**Comment by LuwkasLima** [comment]
@everaldomatias precisamos da sua ajuda aqui. Me confirme se consegue resolver entre hoje e amanha por gentileza.

**Comment by LuwkasLima** [comment]
@everaldomatias essa é a issue da "Single" que na verdade é um CPT das Ações. Essa precisa ser revista por você após fazer a issue #52

**Comment by everaldomatias** [comment]
Veja se é isso @LuwkasLima 

![litoral3-layout-agenda-single-v2](https://cloud.githubusercontent.com/assets/1918474/13270258/a0026d9a-da6b-11e5-9dd4-9541e1abed29.jpg)

**Comment by LuwkasLima** [comment]
@everaldomatias nao tem TEMAS mais!

![image](https://cloud.githubusercontent.com/assets/5949986/13271042/df4ebf76-da57-11e5-972d-6a85b9cad27d.png)

Ta errado o posicionamento dos Icones!

![image](https://cloud.githubusercontent.com/assets/5949986/13271048/efb68236-da57-11e5-850f-281b99a0c523.png)

**Comment by matheusgimenez** [comment]
@LuwkasLima só uma duvida nessa single: no botão de pesquisa na barra avermelhada, qual seria a ação ali? enviamos pro filtro ou pesquisamos no site normal?

**Comment by LuwkasLima** [comment]
Envia pra Agenda de volta e acho que seria bom colocar outro texto: "Busque outra Acao" ou "Faca uma Nova Pesquisa"

**Comment by everaldomatias** [comment]
@LuwkasLima 

![litoral3-layout-agenda-single-v2](https://cloud.githubusercontent.com/assets/1918474/13293895/5fdfce52-db00-11e5-8e73-56f4560d8606.jpg)

**Comment by everaldomatias** [comment]
Tá ai @LuwkasLima 

![litoral3-layout-agenda-single-v2](https://cloud.githubusercontent.com/assets/1918474/13300004/b835556a-db1c-11e5-97b5-2aff0b6f085e.jpg)

**Comment by LuwkasLima** [comment]
@matheusgimenez ficou certinho cara! Esta conseguindo chegar o mais proximo do layout possivel, parabens!

Segue pequenos pontos:

1 - Alinhamento do Texto esta muito pra direita. Precisa ser empurrado um pouco pra esquerda pra ficar proximo do Layout.

![image](https://cloud.githubusercontent.com/assets/5949986/13326068/09aa1ed4-dbaa-11e5-8ee7-561fcba90dcf.png)

Layout:

![image](https://cloud.githubusercontent.com/assets/5949986/13326182/78826dca-dbaa-11e5-8702-5974bd5b7111.png)

2 - Jogar o EIXO e a LUPA um pouco mais centralizado na linha (como no layout). Aproveita pra dar um espaço entre a LUPA e o "Faca uma Nova Pesquisa"

![image](https://cloud.githubusercontent.com/assets/5949986/13326124/3f217b3e-dbaa-11e5-9662-e27176a832cd.png)

![image](https://cloud.githubusercontent.com/assets/5949986/13326151/54ceeaac-dbaa-11e5-9401-1ae6b6fac495.png)

Layout:
![image](https://cloud.githubusercontent.com/assets/5949986/13326160/5d206f6e-dbaa-11e5-8b37-eeb4ae11e2d3.png)

3 - O "quadrado" (box) da Ação na area de Ações Relacionadas está muito "Fino". Se voce comparar com o box no AGENDA vai notar a diferença:

![image](https://cloud.githubusercontent.com/assets/5949986/13326340/11ac5a9c-dbab-11e5-8f80-cf320fe30358.png)

![image](https://cloud.githubusercontent.com/assets/5949986/13326366/2e9ccb96-dbab-11e5-8f55-2d7649d2985b.png)

4 - Eu sei que voce perguntou isso, mas acho que devemos diminuir um pouco o ICONE do box da ação:

![image](https://cloud.githubusercontent.com/assets/5949986/13326414/5f09df44-dbab-11e5-9aed-5ba8b2dbff84.png)

Algumas coisinhas pequenas, mas que deixam a qualidade da entrega a nivel profissional:
- No menu do Dashboard, "Ações" pode ser modificado para "Ações da Agenda"

![image](https://cloud.githubusercontent.com/assets/5949986/13325579/077d327e-dba8-11e5-8560-b686a04ace0b.png)
- "Todas ações" precisa ser "Todas as Ações"

![image](https://cloud.githubusercontent.com/assets/5949986/13325609/27947a86-dba8-11e5-8171-a3d154db0b58.png)
- Não vamos ter mais TEMAS:

![image](https://cloud.githubusercontent.com/assets/5949986/13325621/385025c8-dba8-11e5-952e-dde76a7f1f53.png)

![image](https://cloud.githubusercontent.com/assets/5949986/13325811/05ec3fa8-dba9-11e5-9cf4-8f21b277273e.png)
