### ISSUE TITLE
[Pente Fino] Listagem de "Últimas Notícias" da página CAMARA está quebrando o CSS

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#54]
Listagem de "Últimas Notícias" da página CAMARA está quebrando o CSS:

![image](https://cloud.githubusercontent.com/assets/5949986/13649174/fcab5fb0-e601-11e5-8dac-1d32370e3fea.png)

Link: http://litoralsustentavel.org.br/dialogos-sobre-grandes-empreendimentos-no-litoral-paulista/

**Comment by matheusgimenez** [comment]
Eu acho que eu já tinha resolvido esse em outro issue.. 

Ou eu to tendo um dejavu bem loco hehe.. No mais, enviei um commit agora pra tirar a div de imagem quando o post não tem imagem (tava ficando um espaço estranho).
