### ISSUE TITLE
[Pente Fino] Mudar o texto "Outras agendas em Eixo 1"

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#55]
Mudar o texto Mudar o texto "Outras agendas em Eixo 1" para "Outras **Ações** em Eixo 1"

![image](https://cloud.githubusercontent.com/assets/5949986/13649216/2f74542e-e602-11e5-95a3-6f4ab533d07d.png)

Link: http://litoralsustentavel.org.br/acoes/acao-b/

**Comment by matheusgimenez** [comment]
Feito
