### ISSUE TITLE
[Pente Fino] Mudança na Página Câmara

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#56]
@matheusgimenez precisamos de 2 mudanças na página CAMARAS:

1 - Modificar o nome "Leia Mais" no dashboard para alinhar com o que esta escrito no botão "VEJA MAIS" :+1: 

![image](https://cloud.githubusercontent.com/assets/5949986/13649290/a069d028-e602-11e5-8af7-d5b2e62358ec.png)

![image](https://cloud.githubusercontent.com/assets/5949986/13649313/b0c34e22-e602-11e5-94f2-c47e3a89252f.png)

2 - Hoje esse botão "Veja Mais" é editável ná própria página CAMARA. No entanto, ele faz parte da área de DESTAQUE e deveria ser configurado na página DESTAQUE. Consegue colocar esse Campo para ser editado na Página DESTAQUE ao invez de CAMARA?

![image](https://cloud.githubusercontent.com/assets/5949986/13649356/f49d5c50-e602-11e5-92c6-496ad6779ea5.png)

**Comment by matheusgimenez** [comment]
2: Não consigo. Entendo que fique enrolado, o problema é que não tem um jeito de eu setar fields nessa sub-página.

Existem duas formas, na real, mas nenhuma delas eu acho interessante:

Colocando como um page template ou seja, eu criaria um page template pra página filha somente pra poder fazer a condicional no ACF;

Ou

Colocar em todas páginas filhas da página Câmara.

1: Feito

**Comment by LuwkasLima** [comment]
Sem crise @matheusgimenez, eu convenco a cliente que nao vale a pena..
