### ISSUE TITLE
Pente Fino no Menu "Sanduiche"

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#61]
@willowmagrini so pra deixar mais alinhad com o layout, o @diegorojas sugeriou que o menu tenha as  3 listras brancas quando nao esta em "hover":

![image](https://cloud.githubusercontent.com/assets/5949986/16013599/b446b6e6-3153-11e6-9cb2-2b029738b067.png)

**Comment by LuwkasLima** [comment]
@willowmagrini fazendo outro teste aqui, pensei em uma coisa que ficaria muito boa com esse menu que voce esta propondo e tenho certeza q me ajudaria a convence-las...

Poderiamos deixar o menu mais Dinamico ao ponto de ele so virar "sanduiche" qndo os itens do menu ultrapassarem o espaco disponivel pra eles na primeira linha?

Ou seja:

Assim quando tem poucos itens:

![image](https://cloud.githubusercontent.com/assets/5949986/16015555/db1bf3fa-315b-11e6-9bb8-f2c53585fc6c.png)

Assim quando ultrapassa esse espaco:

![image](https://cloud.githubusercontent.com/assets/5949986/16015571/eb44768a-315b-11e6-9789-063c6d21ed53.png)

**Comment by LuwkasLima** [comment]
@LuwkasLima teste

**Comment by LuwkasLima** [comment]
@willowmagrini da uma olhada nessa ideia, veja se voce acha boa...

**Comment by willowmagrini** [comment]
Eu acho desperdício de horas e jquery a mais sem necessidade,na minha opnião ou deixa de um jeito ou de outro.

**Comment by willowmagrini** [comment]
Pode fechar?

**Comment by LuwkasLima** [comment]
Tudo bem, estou de acordo...
