### ISSUE TITLE
[PERGUNTA] Link do Titulo do Chapéu para Archive de Posts?

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/litoral-sustentavel#63]
@willowmagrini to com um problema que acabei de pensar e que ficou no limbo. A pergunta é a seguinte:

Como faremos para que o usuário do site possa ir ao archive de posts daquela categoria em questão? Por exemplo, digamos que um dos chapéus é "Notícias" e o cara queira ver todas as notícias publicadas. Como faremos para incluir um link no título que leva ao archive?

Obs.: A solução com Brasa Slider for escolhida porque eles queriam o máximo de flexibilidade possível para eleger os posts que vão para o Chapéu da Home (e a unica forma flexivel suficiente era com o Brasa Slider).

Sugestão: Pensei em colocar "hardcoded" o título dos chapéus com o link para o archive de posts referentes aquela categoria. A implicação disso é somente que a funcionalidade que voce desenvolveu para que os chapéus sejam flexíveis (para que eles possam criar vários chapéus na Home) fica inutilizavel.

Veja o que acha...

**Comment by willowmagrini** [comment]
Creio que não necessariamente os posts terão a mesma categoria. Podemos criar um campo extra no slider para colocarem o link da página em questão, seja de categoria, uma busca específica, ou mesmo uma página estática que tenha a ver com todos aqueles posts.

**Comment by LuwkasLima** [comment]
Acho que beleza, minha preocupação era somente de não adicionar mais complexidade para o pessoal que vai gerenciar esses chapeus.

Pensei em uma outra opção, conversei com o @matheusgimenez aqui, mas não chegamos em conclusão se seria melhor ou não, mas vou descrever aqui de qualquer forma:

Sugestão 2: Colocar um campo "Dropbox" que apresenta todas as categorias, para que voce selecione a que você quer que seja apresentada quando o cliente clica no Título. Dai o site leva ao archive daquela categoria. Isso seria para evitar problemas com links mal colocados e direcionaria o tipo de página que o link do título vai ter.

Veja o que acha, mas escolha aquela que melhor lhe convém.

At.,

**Comment by LuwkasLima** [comment]
@willowmagrini estou enviando pra elas sem isso, so pra que mostremos o progresso. Veja se consegue finalizar esse ponto ainda hoje, so pra nao atrapalhar o restante do trabalho.

Vlw!

**Comment by willowmagrini** [comment]
@LuwkasLima 
coloquei o campo link, quando esta preenchido ele cria um link no título para o endereço preenchido.
Prefiro desse jeito para dar mais liberdade , assim os sliders não ficam presos a taxonomia,  podem ser criados sliders de temas transversais e direcionados para uma página simples que tem a ver com todos os slides dele por exemplo. 
Acho que é questão de conversar com elas e ver o que preferem.

**Comment by LuwkasLima** [comment]
@willowmagrini Perfeito!

**Comment by LuwkasLima** [comment]
Ficou bom @willowmagrini !

**Comment by willowmagrini** [comment]
Fechei!
